"""The generated block in a milestone's GitHub tracking PR.

The body is written between markers so a human can keep prose above it and CI
can rewrite the state below it without clobbering that prose.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from rotaris_core.reqtocode.declarations import ReqStatus

if TYPE_CHECKING:
    from milestone_lib.gate import GateResult
    from milestone_lib.progress import MemberProgress, MilestoneProgress

START_MARKER = "<!-- milestone-status:start -->"
END_MARKER = "<!-- milestone-status:end -->"

_TICK = {True: "yes", False: "no"}


def _state(member: MemberProgress) -> str:
    if member.status is ReqStatus.APPROVED:
        return "approved"
    return member.status.value


def _cell(required: bool, present: bool) -> str:
    """Traced/covered only mean something where the requirement demands them."""
    if not required:
        return "n/a"
    return _TICK[present]


def status_block(progress: MilestoneProgress, gate: GateResult) -> str:
    """The markdown between the markers."""
    milestone = progress.milestone
    lines = [
        START_MARKER,
        "",
        f"**{milestone.milestone_id} — {milestone.title}** · target `v{milestone.target_version}`"
        f" · branch `{milestone.branch}` · status `{milestone.status.value}`",
        "",
        f"{progress.done}/{progress.total} requirements approved ({progress.percent}%)"
        f" · {progress.traced} traced · {progress.covered} test-covered",
        "",
    ]
    for group in progress.groups:
        lines += [
            f"#### {group.heading}",
            "",
            "| Requirement | State | Traced | Covered |",
            "| --- | --- | --- | --- |",
        ]
        for member in group.members:
            lines.append(
                f"| [{member.req_id}](../blob/{milestone.branch}/{member.source_path})"
                f" {member.title} | {_state(member)}"
                f" | {_cell(member.trace_required, member.traced)}"
                f" | {_cell(member.test_required, member.covered)} |"
            )
        lines.append("")

    lines += ["#### Gate", "", f"`{gate.summary}`", ""]
    if not gate.ok:
        lines += [f"- {blocker}" for blocker in gate.blockers]
        lines.append("")
    lines += [
        "This block is generated by `devtools/milestone.py pr-body`"
        " and refreshed by `.github/workflows/milestone.yml`. Edit above it, not inside it.",
        "",
        END_MARKER,
    ]
    return "\n".join(lines)


def tracking_pr_body(progress: MilestoneProgress, gate: GateResult, existing: str = "") -> str:
    """The full PR body: any human prose above, then the regenerated block.

    Passing the current body preserves whatever a person wrote above the start
    marker. Anything after the end marker is dropped — the block is meant to be
    last so a reader lands on live state.
    """
    block = status_block(progress, gate)
    if START_MARKER in existing:
        prose = existing.split(START_MARKER, 1)[0].rstrip()
        return f"{prose}\n\n{block}\n" if prose else f"{block}\n"
    if existing.strip():
        return f"{existing.rstrip()}\n\n{block}\n"
    milestone = progress.milestone
    intro = (
        f"Integration branch for **{milestone.milestone_id} — {milestone.title}**.\n\n"
        f"Feature work for this milestone merges here, not into `master`. This PR merges"
        f" when the gate below is green; that merge cuts `v{milestone.target_version}`.\n\n"
        f"Scope and exit criteria: [`{milestone.source_path}`](../blob/"
        f"{milestone.branch}/{milestone.source_path}).\n"
    )
    return f"{intro}\n{block}\n"
