"""The interface a host calls, and the live objects that answer it (SWR-2426).

:class:`RunControl` is deliberately flat and scalar: one method per operation,
arguments a message can carry, and a :class:`ControlResult` back. That shape is
what makes a second implementation — a run in its own process — a swap rather
than a rewrite.

:class:`RunSurface` is the other half: the live run as an in-process host holds
it. It exists so :class:`~rotaris_core.runchannel.inprocess.InProcessRunControl`
can drive a desktop run without this package importing Qt, and so the boundary
between "what a host asks" and "what a run exposes" is written down rather than
implied by whichever attribute the caller happened to reach for.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

from rotaris_core.reqtocode import SWR, traces

if TYPE_CHECKING:
    from rotaris_core.runchannel.messages import ControlResult

__all__ = ["RunControl", "RunSurface"]


@traces(SWR.SWR_2426)
@runtime_checkable
class RunSurface(Protocol):
    """The live run, as the process executing it can reach it.

    Every method may be called while the run is mid-step and from a thread that
    is not the run's own — a window's click handler, typically — so each one is
    expected to be safe from any thread and to answer ``False`` rather than
    raise when the run has already moved past being able to honour it.
    """

    def cancel(self) -> None: ...
    def cancel_pending_questions(self) -> None: ...
    def cancel_pending_approvals(self) -> None: ...
    def pause(self) -> bool: ...
    def cancel_agent(self, agent_id: str) -> bool: ...
    def skip_verifier_check(self) -> bool: ...
    def switch_entry_model(self, model_key: str) -> bool: ...
    def switch_entry_reasoning(self, reasoning: str) -> bool: ...
    def set_permission_mode(self, mode: str) -> bool: ...
    def force_compress(self) -> bool: ...
    def clear_transcript(self) -> bool: ...
    def edit_todo(self, operation: str, target_id: str, text: str = "") -> bool: ...
    def resolve_questions(self, agent_id: str, prompt_id: str, answers: object) -> bool: ...
    def cancel_questions(self, agent_id: str, prompt_id: str) -> bool: ...


@traces(SWR.SWR_2426)
class RunControl(Protocol):
    """Everything a host may ask of a run.

    The implementations differ only in *where* the run is. Nothing here returns
    a live object, and nothing takes one: an argument that cannot be written
    down cannot cross a process boundary, and an interface that allows one
    stops being a boundary the first time somebody uses it.
    """

    # ── prompts waiting on a person ──────────────────────────────────────
    def resolve_approval(self, request_id: str, option: str) -> ControlResult: ...
    def resolve_questions(
        self,
        agent_id: str,
        prompt_id: str,
        answers: dict[str, dict[str, str | None]],
    ) -> ControlResult: ...
    def cancel_questions(self, agent_id: str, prompt_id: str) -> ControlResult: ...

    # ── talking to the agents ────────────────────────────────────────────
    def steer(self, agent_id: str, text: str) -> ControlResult: ...
    def queue_prompt(self, text: str) -> ControlResult: ...
    def edit_queued_prompt(self, prompt_id: str, text: str) -> ControlResult: ...
    def delete_queued_prompt(self, prompt_id: str) -> ControlResult: ...
    def edit_todo(self, operation: str, target_id: str, text: str = "") -> ControlResult: ...

    # ── changing how the run behaves ─────────────────────────────────────
    def switch_entry_model(self, model_key: str) -> ControlResult: ...
    def switch_entry_reasoning(self, reasoning: str) -> ControlResult: ...
    def set_permission_mode(self, mode: str) -> ControlResult: ...
    def force_compress(self) -> ControlResult: ...
    def clear_transcript(self) -> ControlResult: ...

    # ── stopping things ──────────────────────────────────────────────────
    def cancel_agent(self, agent_id: str) -> ControlResult: ...
    def skip_verifier_check(self) -> ControlResult: ...
    def pause(self) -> ControlResult: ...
    def cancel(self) -> ControlResult: ...

    # ── the terminal the agent is using ──────────────────────────────────
    def send_keys(self, stream_id: str, text: str, enter: bool = False) -> ControlResult: ...
    def resize_terminal(self, stream_id: str, cols: int, rows: int) -> ControlResult: ...
    def interrupt_terminal(self, stream_id: str) -> ControlResult: ...
    def kill_terminal(self, stream_id: str) -> ControlResult: ...
