"""Local access to the third-party notice bundle shipped with this build (SWR-3720).

The bundle is generated by ``packaging/third_party_licences.py`` into the asset
directory, committed with the release, and walked into every standalone artifact
by the PyInstaller data collection. About & Legal reads it from here — offline,
from the build the user is actually running, never from the network.
"""

from __future__ import annotations

from pathlib import Path

from rotaris_core.reqtocode import SWR, traces


@traces(SWR.SWR_3720)
def notice_bundle_path() -> Path:
    """Absolute path of the bundled notice file.

    Resolved through ``__file__`` like the font directory: the one expression
    that holds for a checkout and for a frozen build.
    """
    return Path(__file__).resolve().parent / "assets" / "THIRD-PARTY-LICENSES.txt"


@traces(SWR.SWR_3720)
def read_notice_bundle() -> str | None:
    """The bundled third-party notices, or None when this build carries none."""
    try:
        text = notice_bundle_path().read_text(encoding="utf-8")
    except OSError:
        return None
    return text or None
